---
ID: "8e7f4f7d-8ac7-435a-bb13-8212313c98d4"
Parent: "348162cf-d211-43b5-a745-dc5c8f62d677"
Template: "ab86861a-6030-46c5-b394-e8f99e8b87db"
Path: /sitecore/templates/Project/PLAY/JSS Settings
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: Office/32x32/gearwheels.png
- ID: "12c33f3f-86c5-43a5-aeb4-5598cec45116"
  Hint: __Base template
  Value: |
    {EC848505-D30C-4BDC-A0AA-7CC9D320085E}
    {CBC14160-BED0-4AA2-9387-4C13179205B9}
    {A7228B46-610D-4A17-9F61-649F3A30AAAE}
    {59F55DFC-4DB7-422F-9D40-F2ECF66C8499}
- ID: "f7d48a55-2158-4f02-9356-756654404f73"
  Hint: __Standard values
  Value: "{016A0A40-4CCB-47A9-83B9-8DABB97EF2F2}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d9f7f2b5-eca6-4842-a745-359301a2ed09"
