---
ID: "798d1ed3-b717-5b2b-b4c6-5ea39979737d"
Parent: "7dfc82e1-f7a7-5853-9760-59c812f25776"
Template: "7dfc82e1-f7a7-5853-9760-59c812f25776"
Path: /sitecore/templates/Project/Global/ProductCategoriesGrid/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "60b5ef3a-b78b-411b-a19b-0ef75656b8a2"
