---
ID: "7f290216-4b34-4c3b-a5ee-b1a8f4a68039"
Parent: "d8aa73e1-c275-4eee-bb9d-333925e51952"
Template: "d8aa73e1-c275-4eee-bb9d-333925e51952"
Path: /sitecore/templates/Project/PLAY/Legacy/CMP Entities/Session/__Standard Values
SharedFields:
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: 
- ID: "c9283d9e-7c29-4419-9c28-5a5c8ff53e84"
  Hint: __Bucketable
  Value: 1
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{96E5F4BA-A2CF-4A4C-A4E7-64DA88226362}" />
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "2063a900-230c-4172-ba19-c00992f363f7"
      Hint: ImageTransformation
      Value: web
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{C55B483C-EA7F-4E76-A066-985F7D9396CA}"
    - ID: "8058e5a0-d20d-4923-b87d-f56b19efc20f"
      Hint: Name
      Value: $name
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "05597c00-d8f5-4a8d-a21a-83aec12e0d99"
