---
ID: "a988761c-2447-57b7-b0cd-5c72294a9460"
Parent: "fdf43aad-c5d1-54e4-9909-59bfddc86689"
Template: "fdf43aad-c5d1-54e4-9909-59bfddc86689"
Path: /sitecore/templates/Project/Global/FeaturedSpeakers/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "b0c4fa40-f023-4185-9315-6f4e29a902e9"
