---
ID: "dea04878-0854-46e8-a6ff-cdcdd960e3b9"
Parent: "26385370-1739-4f4f-84c0-cbd96e9514c0"
Template: "26385370-1739-4f4f-84c0-cbd96e9514c0"
Path: /sitecore/templates/Project/PLAY/App Route/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {26385370-1739-4F4F-84C0-CBD96E9514C0}
    {C14B6289-8AC2-439C-9E5B-40DE9F820C3F}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "5a2d89b5-f7e7-42e8-b13c-d4396907f20b"
    - ID: "e44ef569-9a34-4219-af40-3d0529984022"
      Hint: Title
      Value: $name
