---
ID: "5caf57aa-70f2-56af-a023-2ed118bafa20"
Parent: "32607765-7441-5a23-a7f6-b8f0b9994c44"
Template: "32607765-7441-5a23-a7f6-b8f0b9994c44"
Path: /sitecore/templates/Project/Global/SelectedSponsorsGrid/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "3f2d33c5-966c-4909-8ce9-800726b20935"
