---
ID: "2de46343-6a33-58a9-8076-7b2ab5737737"
Parent: "6db09cef-64a8-52a3-a980-38408109c4d7"
Template: "6db09cef-64a8-52a3-a980-38408109c4d7"
Path: /sitecore/templates/Project/Global/Webpage/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: 
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{8F0E1432-3729-462B-AD20-DAF067694BCB}"
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{96E5F4BA-A2CF-4A4C-A4E7-64DA88226362}" />
    </r>
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "eb09effc-c6c4-416b-ba5e-99555b2635a4"
    - ID: "ed69eacf-5eb2-5050-9d5b-997812318dde"
      Hint: pageTitle
      Value: $name
